"""Infrastructure-neutral broker contract."""

from collections.abc import AsyncIterator
from typing import AsyncContextManager, Protocol

from deeptrace.runtime.models import JobMessage, StoredEvent


class ResearchBroker(Protocol):
    async def ensure_group(self) -> None: ...

    async def enqueue(self, run_id: str) -> str: ...

    async def read(self, *, block_ms: int = 5_000) -> list[JobMessage]: ...

    async def reclaim_stale(self) -> list[JobMessage]: ...

    async def ack(self, message_id: str) -> None: ...

    async def request_cancel(self, run_id: str) -> None: ...

    async def is_cancel_requested(self, run_id: str) -> bool: ...

    async def clear_cancel(self, run_id: str) -> None: ...

    async def publish_event(self, event: StoredEvent) -> None: ...

    def subscription(
        self, run_id: str
    ) -> AsyncContextManager[AsyncIterator[int]]: ...
